export const routePaths = {
  notification: '/notification',
  productList: '/products',
  openAccount: '/open-account',
  changeProfile: '/change-profile',
  appointment: '/appointment',
  branchDirectory: '/branch-directory',
  appointmentManagement: '/appointment/management',
  bookAppointment: '/appointment/book',
  cards: '/cards',
  addNewCard: '/cards/new',
  activeCard: '/cards/active',
  reissueCard: '/cards/reissue',
  reportLostCard: '/cards/report-lost',
  releaseCard: '/cards/release',
  transferLimitSetting: '/transfer-limit-setting',
  eAlertsManagement: '/e-alerts-management',
  eAlertsBalance: '/e-alerts-balance',
  signUp: '/sign-up',
  termCondition: '/terms-conditions',
};
