export const ProductInterestRateFeatureName = 'productInterestRate';
export const ActionType = {
  INQUIRY_PRODUCT_INTEREST_RATE_REQUEST_SUCCESS: `${ProductInterestRateFeatureName}/INQUIRY_PRODUCT_INTEREST_RATE_REQUEST_SUCCESS`,
  INQUIRY_PRODUCT_INTEREST_RATE_REQUEST_FAILED: `${ProductInterestRateFeatureName}/INQUIRY_PRODUCT_INTEREST_RATE_REQUEST_FAILED`,
  INQUIRY_PRODUCT_INTEREST_RATE_REQUEST: `${ProductInterestRateFeatureName}/INQUIRY_PRODUCT_INTEREST_RATE_REQUEST`,
};
