import React from 'react';

const WaveDivider = () => {
  return (
    <svg
      width="375"
      height="8"
      viewBox="0 0 375 8"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g>
        <circle
          cx="3.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="21.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="38.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="56.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="73.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="91.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="108.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="126.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="143.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="161.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="178.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="196.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="213.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="231.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="248.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="266.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="283.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="301.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="318.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="336.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="353.75"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
        <circle
          cx="371.25"
          cy="0.4375"
          r="5.5"
          fill="white"
        />
      </g>
    </svg>
  );
};

export default WaveDivider;
