export const FeatureName = 'account';
export const ActionType = {
  GET_ACCOUNT_LIST_REQUEST_SUCCESS: `${FeatureName}/GET_ACCOUNT_LIST_REQUEST_SUCCESS`,
  GET_ACCOUNT_LIST_REQUEST_FAILED: `${FeatureName}/GET_ACCOUNT_LIST_REQUEST_FAILED`,
  GET_ACCOUNT_LIST_REQUEST: `${FeatureName}/GET_ACCOUNT_LIST_REQUEST`,
  CLEAN_UP: `${FeatureName}/CLEAN_UP`,
};
