export const FeatureDebitCardName = 'debitCard';

export const ActionType = {
  DEBIT_CARD_REQUEST: `${FeatureDebitCardName}/DEBIT_CARD_REQUEST`,
  DEBIT_CARD_REQUEST_SUCCESS: `${FeatureDebitCardName}/DEBIT_CARD_REQUEST_SUCCESS`,
  DEBIT_CARD_REQUEST_FAILED: `${FeatureDebitCardName}/DEBIT_CARD_REQUEST_FAILED`,
  DEBIT_CARD_SELECTED: `${FeatureDebitCardName}/DEBIT_CARD_SELECTED`,
  DEBIT_CARD_REFRESH_SUCCESS: `${FeatureDebitCardName}/DEBIT_CARD_REFRESH_SUCCESS`,
  DEBIT_CARD_SET_LOADING: `${FeatureDebitCardName}/DEBIT_CARD_SET_LOADING`,

  ACTIVATE_CARD_REQUEST: `${FeatureDebitCardName}/ACTIVATE_CARD_REQUEST`,
  ACTIVATE_CARD_REQUEST_SUCCESS: `${FeatureDebitCardName}/ACTIVATE_CARD_REQUEST_SUCCESS`,
  ACTIVATE_CARD_REQUEST_FAILED: `${FeatureDebitCardName}/ACTIVATE_CARD_REQUEST_FAILED`,
  ACTIVATE_CARD_RESET: `${FeatureDebitCardName}/ACTIVATE_CARD_RESET`,

  TRANSACTION_REQUEST: `${FeatureDebitCardName}/TRANSACTION_REQUEST`,
  TRANSACTION_REQUEST_SUCCESS: `${FeatureDebitCardName}/TRANSACTION_REQUEST_SUCCESS`,
  TRANSACTION_REQUEST_FAILED: `${FeatureDebitCardName}/TRANSACTION_REQUEST_FAILED`,
  TRANSACTION_EMPTY_LIST: `${FeatureDebitCardName}/TRANSACTION_EMPTY_LIST`,

  MANAGE_CARD_PIN_REQUEST: `${FeatureDebitCardName}/MANAGE_CARD_PIN_REQUEST`,
  MANAGE_CARD_PIN_REQUEST_SUCCESS: `${FeatureDebitCardName}/MANAGE_CARD_PIN_REQUEST_SUCCESS`,
  MANAGE_CARD_PIN_REQUEST_FAILED: `${FeatureDebitCardName}/MANAGE_CARD_PIN_REQUEST_FAILED`,

  COMMON_CODE_LIST_REQUEST: `${FeatureDebitCardName}/COMMON_CODE_LIST_REQUEST`,
  COMMON_CODE_LIST_REQUEST_SUCCESS: `${FeatureDebitCardName}/COMMON_CODE_LIST_REQUEST_SUCCESS`,
  COMMON_CODE_LIST_REQUEST_FAILED: `${FeatureDebitCardName}/COMMON_CODE_LIST_REQUEST_FAILED`,

  SEARCH_TRANSACTION: `${FeatureDebitCardName}/SEARCH_TRANSACTION`,
  RESET_TRANSACTIONS: `${FeatureDebitCardName}/RESET_TRANSACTIONS`,

  FILTER_TRANSACTIONS_BY_TYPE: `${FeatureDebitCardName}/FILTER_TRANSACTIONS_BY_TYPE`,
  REPORT_CARD_LOST_REQUEST: `${FeatureDebitCardName}/REPORT_CARD_LOST_REQUEST`,
  REPORT_CARD_LOST_REQUEST_SUCCESS: `${FeatureDebitCardName}/REPORT_CARD_LOST_REQUEST_SUCCESS`,
  REPORT_CARD_LOST_REQUEST_FAILED: `${FeatureDebitCardName}/REPORT_CARD_LOST_REQUEST_FAILED`,

  MANAGE_LIMIT_REQUEST: `${FeatureDebitCardName}/MANAGE_LIMIT_REQUEST`,
  MANAGE_LIMIT_REQUEST_SUCCESS: `${FeatureDebitCardName}/MANAGE_LIMIT_REQUEST_SUCCESS`,
  MANAGE_LIMIT_REQUEST_FAILED: `${FeatureDebitCardName}/MANAGE_LIMIT_REQUEST_FAILED`,

  CHOOSE_NEW_CARD_TEMPLATE: `${FeatureDebitCardName}/CHOOSE_NEW_CARD_TEMPLATE`,

  CARD_VERIFICATION_DATA: `${FeatureDebitCardName}/CARD_VERIFICATION_DATA`,

  CARD_SET_AMOUNT: `${FeatureDebitCardName}/CARD_SET_AMOUNT`,

  FOCUS_CARD: `${FeatureDebitCardName}/FOCUS_CARD`,

  SHOW_CALENDAR: `${FeatureDebitCardName}/SHOW_CALENDAR`,

  RESET_REDUX: `${FeatureDebitCardName}/RESET_REDUX`,
};

export const debitCardsURLs = {
  GET_CARDS: '/kh/ca/KHCA001.pwkjson',
  ACTIVATE_CARD: '/kh/ca/KHCA008.pwkjson',
  GET_TRANSACTION: '/kh/ca/KHCA002.pwkjson',
  MANAGE_CARD_PIN: '/kh/ca/KHCA003.pwkjson',
  REPORT_CARD_LOST: '/kh/ca/KHCA004.pwkjson',
  COMMON_CODE_LIST: '/gm/co/GMCO004.pwkjson',
  MANAGE_LIMIT: '/kh/ca/KHCA005.pwkjson',
  INQUIRY_ADDRESS: '/kh/ca/KHCA007.pwkjson',
  INQUIRY_BRANCH: '/kh/co/KHCO002.pwkjson',
  INQUIRY_CUSTOMER: '/gm/co/GMCO017.pwkjson',
  INQUIRY_EMPLOYEE: '/kh/co/KHCO004.pwkjson',
  CARD_ISSUANCE: '/kh/ca/KHCA006.pwkjson',
  GET_ACCOUNT: '/kh/iq/KHIQ005.pwkjson'
};
