export const endpoints = {
  uploadFile: '/jsp/photoFileUpload.jsp?upload_type=addr',
  getAccountList: '/ca/iq/CAIQ006.pwkjson',
  openAccount: '/ca/pr/CAPR020.pwkjson',
  inquiryProductInterestRate: '/ca/pr/CAPR002.pwkjson',
  inquiryUserInformation: '/ca/me/CAME001.pwkjson',
  requestGetEmailVerifyCode: '/ca/se/CASE001.pwkjson',
  sendEmailVerifyCode: '/ca/se/CASE002.pwkjson',
  changeUserInfoPreTransaction: '/ca/me/CAME002.pwkjson',
  changeUserInfoTransaction: '/ca/me/CAME003.pwkjson',
  inquiryETransferCustomerInfo: '/ca/tr/CATR028.pwkjson',
  getAppointments: '/ca/hc/CAHC002.pwkjson',
  cancelAppointment: '/ca/hc/CAHC003.pwkjson',
  getBranchDirectory: '/ca/co/CACO006.pwkjson',
  bookAppointment: '/ca/hc/CAHC001.pwkjson',
  getBankingTransferLimit: '/ca/me/CAME004.pwkjson',
  changeTransferLimit: '/ca/me/CAME005.pwkjson',
  cancelRequestChangeLimit: '/ca/me/CAME006.pwkjson',
  getEAlertSetting: '/ca/st/CAST003.pwkjson',
  getTransactionNotify: '/ca/ho/CAHO001.pwkjson',
  getOffersNotify: '/ca/ho/CAHO001.pwkjson',
  getPromotionNotify: '/ca/ho/CAHO002.pwkjson',
};
