export const AppNotificationFeatureName = 'app__notification';

export const ActionType = {
  GET_TRANSACTIONS_NOTIFY_REQUEST: `${AppNotificationFeatureName}/GET_TRANSACTIONS_NOTIFY_REQUEST`,
  GET_TRANSACTIONS_NOTIFY_REQUEST_SUCCESS: `${AppNotificationFeatureName}/GET_TRANSACTIONS_NOTIFY_REQUEST_SUCCESS`,
  GET_TRANSACTIONS_NOTIFY_REQUEST_FAILED: `${AppNotificationFeatureName}/GET_TRANSACTIONS_NOTIFY_REQUEST_FAILED`,

  GET_OFFERS_NOTIFY_REQUEST: `${AppNotificationFeatureName}/GET_OFFERS_NOTIFY_REQUEST`,
  GET_OFFERS_NOTIFY_REQUEST_SUCCESS: `${AppNotificationFeatureName}/GET_OFFERS_NOTIFY_REQUEST_SUCCESS`,
  GET_OFFERS_NOTIFY_REQUEST_FAILED: `${AppNotificationFeatureName}/GET_OFFERS_NOTIFY_REQUEST_FAILED`,

  GET_PROMOTIONS_NOTIFY_REQUEST: `${AppNotificationFeatureName}/GET_PROMOTIONS_NOTIFY_REQUEST`,
  GET_PROMOTIONS_NOTIFY_REQUEST_SUCCESS: `${AppNotificationFeatureName}/GET_PROMOTIONS_NOTIFY_REQUEST_SUCCESS`,
  GET_PROMOTIONS_NOTIFY_REQUEST_FAILED: `${AppNotificationFeatureName}/GET_PROMOTIONS_NOTIFY_REQUEST_FAILED`,
  GET_BANNER_SEQ: `${AppNotificationFeatureName}/GET_BANNER_SEQ`,
  SET_TAB_INDEX: `${AppNotificationFeatureName}/SET_TAB_INDEX`,
  CLEAN_UP: `${AppNotificationFeatureName}/CLEAN_UP`,
};
