export const APP_GLOBAL = 'app_global';

export const ActionType = {
  REDIRECT_REQUEST: `${APP_GLOBAL}/REDIRECT_REQUEST`,
  LANGUAGE_REQUEST: `${APP_GLOBAL}/LANGUAGE_REQUEST`,
  BACK_EVENT: `${APP_GLOBAL}/BACK_EVENT`,
  APP_LOGIN: `${APP_GLOBAL}/APP_LOGIN`,
  NATIVE_PARAMS: `${APP_GLOBAL}/NATIVE_PARAMS`,
  APP_PATH: `${APP_GLOBAL}/APP_PATH`,
};
